ohtuprojekti-Kierratysavustin/Kierratysavustin

README.md

Tässä demosin feature branchejä.

demotaan feature bracnh prosessia

---

README.md

Tehtiin Nikon kanssa DoD-kuvaus.

Definition of Done lisätty

---

client/.eslintignore
client/.eslintrc.js
client/cypress/integration/recycling-app.spec.js
client/package-lock.json
client/package.json
client/src/App.js
client/src/index.js

Alustava hyvin alkeellinen luonnos tuotteiden listaus sivusta, josta tällä hetkellä voi avata kierrätysohjeet nappia painamalla selaimen alert popup ikkunaan. Lisäksi joitain e2e testejä tehdyille ominaisuuksille.
Samalla testailin myös jsdoc dokumentaation kirjoittamista ja sekin näyttää toimivan ihan kätevästi, tosin tässä vaiheessa vaan ei kauheasti mitään dokumentoitavaa vielä ole, eli täytyy palata asiaan vielä joskus myöhemmin.
Nämä muokkaukset siis vaan alustavaa hahmottelua ja toteutus on hyvin primitiivinen, mutta näin sovellukseen tuotu jo jotain toiminnallisuutta.

Listaus sivu

---

client/cypress/integration/recycling-app.spec.js
client/package-lock.json
client/package.json
client/src/App.js
client/src/components/Product.js
client/src/components/ProductList.js

Testailin react routerin käyttöönottoa samalla kun tein tuotekohtaisia sivuja ja näyttää toimivan hyvin. Tässä listaus-sivu, josta linkit tuotteiden sivulle, ja lisäksi laitoin myös tuotteiden lisäys formin omalle sivulle. 
Lokaalissa dockerissa pyörii ilman säätämistä, mutta epäilen vähän, että vaatii vielä säätämistä, että toimii staging serverillä.

React router testi

---

server/index.js

routing korjattu

---

client/cypress/integration/recycling-app.spec.js
client/package-lock.json
client/package.json
client/src/components/InstructionForm.js
client/src/components/Product.js

Lisättiin alustava formi tuotesivulle kierrätys ohjeiden tekemiseen. Samaa formia voi käyttää kommentti formien lisäämisen pohjana. huom. staging branch muuttui samalla kuin koodattiin, jotain merge conflictia täytyy selvitellä.

kierrätys formi lisätty

---

client/cypress.json
client/package-lock.json
client/src/index.js
nginx.conf
server/index.js

Backendin tiedostossa index.js oleva app.get("*", (req, res) => res.sendFile(path.resolve("build", "index.html"))) tulee olla muiden pyyntöjen jälkeen, muuten kaikkiin pyyntöihin vastataan static tiedostoilla.
npm install valitti jotain high severity vulnerabilitya jonkin immer version takia, joten päivitin sen.

browserRouterin pitäisi toimia taas

---

.vscode/settings.json

Ehdottaisin, että otettaisiin yhteisesti käyttöön tällainen vscode setup. Kaikkien siis tulisi asentaa ESLint plugari jolloin tämän jälkeen jokaisen tallennuksen yhteydessä tapahtuu automaattisesti eslint --fix, joka korjaa kaikki sisennyksiin, lainausmerkkeihin, yms. liittyvät ongelmat, ilman, että niitä täytyy itse muuttaa. Tällöin myös koodin tyyli pysyy automaattisesti yhtenäisempänä, kun vscode muokkaa koodia automaattisesti oikeaan muotoon eslint määrittelyiden mukaisesti.
Muistelen, että oli puhetta, että käytetään tietokannan_alustus branchia pohjana, niin tein tämän muokkauksen tuosta branchista lähtien, mutta käytännössä siis tarvitaan vain projektin juurikansioon .vscode kansio ja sinne tuo settings.json tiedosto, eli tässä ei varsinaisesti tule mitään koodiin liittyvää …

Lisätty vscoden settings.json tiedosto

---

client/package-lock.json
client/package.json
client/src/components/RegisterForm.js
client/src/services/products.js
server/controllers/users.js

Syötteessä olevaa virheilmoitusta ei näe jos ei klikka pois teksti laatikosta.

Rekisteroitymisformi validointi

---

client/src/components/RegisterForm.js

Rekisteröitymisformissa luki hieman hassusti "Sign in to continue". Vaihdoin siihen "Rekisteröidy". Jos on parempia ehdotuksia niin muokatkaa.

rekisteroitymisformin headerin muokkaus

---

client/src/components/Notification.js
client/src/components/RegisterForm.js
client/src/components/notification.css
client/src/services/register.js
server/controllers/users.js
server/models/user.js

Lisätty simppeli ilmoitus kun käyttäjä luodaan. 
Ongelmana kuitenkin se että ilmoitetaan että käyttäjä luodaan vaikkakin käyttäjä samalla nimellä olisi jo olemassa eikä uutta samalla nimellä olevaa käyttäjää pystykkään luoda. 
Itse yritin pitkään saada axios responsen ja serverille tehtävän get pyynnön avulla tehdä ratkaisua tähän onglemaan. En kuitenkaan saanut mitään puhdasta ratkaisua tehtyä joten jätin sen tekemättä.

lisätty simppeli ilmoitus rekisteröintiin

---

server/app.js
server/index.js
server/jest.config.js
server/package-lock.json
server/package.json
server/requests/all_products.rest
server/tests/kierratysavustin_api.test.js

Lisäsin alustavan setupin jest testeille backendissä. Muutin sovelluksen rakennetta fullstack kurssin esimerkkien mukaan siten, että pelkän index.js sijaan sovelluksessa on app.js ja index.js. Kaikki näyttää toimivan lokaalisti dockerissakin ilman ongelmia, eli vaikuttaa ok:lta.
Testeissä on tässä vaiheessa vain testi sille, että backendin api palauttaa jotain json muodossa. Tuota voi sitten lähteä laajentamaan ja lisäämään testejä tämän pohjan päälle.
btw. Backendissa pitäisi varmaan ottaa käyttöön eslint, koska siellä on nyt aika kirjavaa käytäntöä, esim. osa riveistä päättyy ";" ja osassa sitä ei ole jne.

Jest testien alustus backendiin

---

client/package-lock.json
client/package.json
client/src/App.js
client/src/components/InstructionForm.js
client/src/components/Product.js
client/src/components/ProductForm.js
client/src/components/SearchForm.js
client/src/services/products.js
client/src/tests/RegisterForm.test.js
e2e_tests/cypress/integration/recycling-app.spec.js

Otettiin Nicholaksen kanssa tilanhallintaa varten käyttön [zustand](https://github.com/pmndrs/zustand)-kirjasto. Se on suuhteellisen helppokäyttöinen ja boilerplatea tulee paljon vähemmän kuin esimerkiksi reduxissa. Saatiin kirjaston avulla kierrätysohjeet päivittymään heti lisäyksen jälkeen.

tilanhallinta

---

README.md
documents/teknologiat.md

Alustava lista teknologioista. Missasin varmaan jotain teknologioita ja osassa voi olla vähän huonot selitykset, niin lisäilkää vaan jos puuttuu.

Teknologialista

---

client/src/App.js
client/src/components/Product.js
client/src/components/ProductForm.js

Ehdotettuja muokkausia pullariin #40 lisättäväksi.

Muokattu näkymiä kirjautumiseen perustuen

---

server/requests/one_product.rest
server/tests/kierratysavustin_api.test.js

Lisäsin muutamia perus testejä backendin puolelle.

Lisää jest testejä backendiin

---

client/src/components/InstructionForm.js
server/.eslintignore
server/.eslintrc.js
server/app.js
server/controllers/login.js
server/controllers/products.js
server/controllers/tests.js
server/controllers/users.js
server/index.js
server/jest.config.js
server/models/comment.js
server/models/instruction.js
server/models/product.js
server/models/user.js
server/package-lock.json
server/package.json
server/tests/kierratysavustin_api.test.js

Eslint käyttöön backendissä ja samalla ajettu korjaukset (eslint --fix) kaikille tiedostoille.

Eslint käyttöön backendissä

---

client/src/components/InstructionForm.js
server/.eslintignore
server/.eslintrc.js
server/app.js
server/controllers/login.js
server/controllers/products.js
server/controllers/tests.js
server/controllers/users.js
server/index.js
server/jest.config.js
server/models/comment.js
server/models/instruction.js
server/models/product.js
server/models/user.js
server/package-lock.json
server/package.json
server/requests/login.rest
server/requests/new_product.rest
server/requests/one_product.rest
server/requests/user_product.rest
server/tests/kierratysavustin_api.test.js

Suosikkituotteiden lisäystoiminto + testit lisätty backendiin. Katsoin miten kierrätysohjeiden lisäys oli toteutettuna tietokannassa ja tein samalla mallilla suosikkituotteiden lisäämisen siten, että tuotteet pitää kirjaa käyttäjistä, joiden suosikkina ovat ja käyttäjät pitää kirjaa omista suosikkituotteistaan.
Käytin pohjana branchiä, jossa on eslint käytössä, että asettelut pysyy siistinä, eli #54 kannattaa varmaan mergetä ennen tätä.

Suosikkituotteiden lisäys käyttäjälle backendissä

---

client/src/components/FavouriteProducts.js
client/src/components/SearchForm.js
client/src/tests/FavouriteProducts.test.js

fronttiin lisätty nyt simppeli favourite products komponentti, joka on vain näkyvissä jos käyttäjä on kirjautunut sisään.

lisätty FavouriteProducts komponentti ja 1 testi

---

client/src/components/ProductForm.js
client/src/services/products.js
server/controllers/products.js
server/controllers/users.js
server/models/instruction.js
server/models/user.js
server/requests/dislike_instruction.rest
server/requests/like_instruction.rest
server/requests/new_Instruction.rest
server/requests/new_product.rest
server/requests/new_user.rest
server/requests/undislike_instruction.rest
server/requests/unlike_instruction.rest
server/tests/kierratysavustin_api.test.js

Tykkäystoiminto bäkkäriin.
Post pyyntö users/likes/{instruction.id}/ lisää käyttäjän tykkäyksiin ohjeen ja päivittää ohjeen score arvoa. 
Put pyyntö users/likes/{instruction.id}/ poistaa käyttäjän tykkäyksistä ohjeen ja päivittää ohjeen score arvoa. 
Ja samat dislikeille osoitteeseen users/dislikes/{instruction.id}/. 
Mietin aluksi käyttäväni delete pyyntöä poistamiseen, mutta sillä ei ilmeisesti voi palauttaa "päivitettyä" käyttäjää (eikä mitään muutakaan). Jos palautusta ei tarvita frontissa voidaan käyttää deleteä.
Kun tuotteet haetaan ja ohjeet populoidaan palautetaan ohjeen ohjeistuksen lisäksi score arvo.
Testien kanssa oli vähän säätöä, kannattaa ehkä kattoa oisko niissä jotain korjattavaa. 
Tässä nyt käytetään ohjeen scoressa vain laskuria.

Tykkays backend

---

client/src/App.js
client/src/components/LoginForm.js
client/src/components/Product.js
client/src/components/VoteForm.js
client/src/services/products.js
client/src/tests/Vote.test.js
e2e_tests/cypress/integration/recycling-app.spec.js
server/controllers/users.js

Loginfromi refreshaa sovelluksen kun en nyt keksiny nopeasti miten saisin haettua servulta kirjauduttaessa tykkäykset muuten. Yritän korjata tämän perjantaina, jos ette halua vielä mergetä.

Tykkays frontti

---

client/src/components/Product.js
client/src/components/SearchBarForm.js
client/src/components/VoteForm.js
client/src/tests/Product.test.js
client/src/tests/ProductList.test.js
client/src/tests/SearchForm.test.js
client/src/tests/Vote.test.js
e2e_tests/cypress/integration/recycling-app.spec.js

Tässä pullarissa tällä hetkellä korjattuna ainakin jotenkin clientin jest testit. Koitan ehtiä vielä kattoa e2e testejä jonkin aikaa, mutta en tiedä ehdinkö saada niitä toimimaan tänään.

Testien korjausta

---

server/models/comment.js

Server models comment.js poistettu

Comment js poisto

---

client/src/components/FavoritesForm.js
client/src/components/VoteForm.js

Branchin nimi on vähän harhaan johtava sillä alkuun oletin, että tiedot pitäisi tallentaa selaimen muistiin. Bugin sai kuitenkin korjattua lisäämällä sivun päivittämisen yhteyteen toiminallisuuden joka tarkistaa jo olevista listoista onko tykkäyksiä/suosikkeja.

Sivun päivittämisen korjaus

---

client/package-lock.json
client/package.json
e2e_tests/package-lock.json
e2e_tests/package.json
server/controllers/products.js
server/controllers/users.js
server/models/user.js
server/package-lock.json
server/package.json
server/utils/auth.js
server/utils/config.js

Autentikoinnin refaktorointi niin, että olemassa yksi util funktio, jota kutsumalla hoidetaan autentikointi. Poistaa copypastea, erityisesti kun lisätään uusia controllereja, jotka tarvitsevat ensin autentikoinnin.

Autentikoinnin refaktorointi

---

documents/Backend-dokumentaatio.md
documents/kayttoohje.md

Docker hub paivitys testi

---

client/src/components/NavigationBar.tsx

Docker hub testailua

---

server/models/productUserCounter.js

Max validaattori skeemaan molemmille laskureille. Max arvoksi: 1e17
closes #123

Max arvo ProductUserCount laskurille
